# Check one hot encoded dataset

In [45]:
import os

os.chdir("/home/aneta/Desktop/ZZSN/code/polyphonic-music-modeling")

In [46]:
!pwd

/home/aneta/Desktop/ZZSN/code/polyphonic-music-modeling


In [47]:
import numpy as np
import torch
import typing as t
from scripts.dataset import dataset_loading as dl

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [48]:
DATASET_PATH = os.path.join(os.getcwd(), "data", "dataset", "train")
#DATASET_PATH = os.path.join(os.getcwd(), "data", "dataset", "my")

In [49]:
dataset = dl.MusicDataset(dataset_root=DATASET_PATH)

In [50]:
data = dataset[156]
print(data)

(tensor([12,  4, 25,  1,  5,  1, 12,  3,  2, 11,  3,  2, 11,  3,  2, 11,  3,  2,
         6, 11, 12,  4, 12,  3,  2, 11,  3,  2, 11,  3,  2, 11,  3,  2,  6, 11,
        12,  4,  1,  5,  1, 14,  3,  2,  5,  3,  2, 12,  3,  2,  5,  3,  2,  6,
         9,  3,  2,  5,  3,  2, 11,  3,  2,  5,  3,  2,  4, 24,  1, 16,  1,  9,
         3,  2,  8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  9,  3,  2,
         8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  1, 16,  1,  9,  3,
         2,  8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  6, 30, 38,  1,
        16,  1, 12, 12,  6, 19,  3,  2, 14,  3,  2, 12,  3,  2, 19,  3,  2,  4,
        24,  1,  5,  1, 14,  3,  2, 12,  3,  2,  9,  3,  2, 14,  3,  2,  6,  1,
        16,  1, 12, 11,  3,  2,  9,  3,  2, 25,  4,  6, 30,  2,  1, 16,  1, 12,
        12,  3,  2, 12,  3,  2,  6,  1, 10,  1, 14,  3,  2, 12,  3,  2, 14,  3,
         2, 19,  3,  2,  4,  1,  5,  1, 22, 17, 11,  3,  2,  9,  3,  2,  4,  4,
         4, 25,  1,  5,  1, 12, 34,  1,

In [51]:
x=data[0]
print(x)
print(type(x))
x=np.array(x)

tensor([12,  4, 25,  1,  5,  1, 12,  3,  2, 11,  3,  2, 11,  3,  2, 11,  3,  2,
         6, 11, 12,  4, 12,  3,  2, 11,  3,  2, 11,  3,  2, 11,  3,  2,  6, 11,
        12,  4,  1,  5,  1, 14,  3,  2,  5,  3,  2, 12,  3,  2,  5,  3,  2,  6,
         9,  3,  2,  5,  3,  2, 11,  3,  2,  5,  3,  2,  4, 24,  1, 16,  1,  9,
         3,  2,  8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  9,  3,  2,
         8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  1, 16,  1,  9,  3,
         2,  8,  3,  2,  8,  3,  2,  8,  3,  2,  6,  8,  9,  4,  6, 30, 38,  1,
        16,  1, 12, 12,  6, 19,  3,  2, 14,  3,  2, 12,  3,  2, 19,  3,  2,  4,
        24,  1,  5,  1, 14,  3,  2, 12,  3,  2,  9,  3,  2, 14,  3,  2,  6,  1,
        16,  1, 12, 11,  3,  2,  9,  3,  2, 25,  4,  6, 30,  2,  1, 16,  1, 12,
        12,  3,  2, 12,  3,  2,  6,  1, 10,  1, 14,  3,  2, 12,  3,  2, 14,  3,
         2, 19,  3,  2,  4,  1,  5,  1, 22, 17, 11,  3,  2,  9,  3,  2,  4,  4,
         4, 25,  1,  5,  1, 12, 34,  1, 

In [53]:
data = dataset[6]
print(type(data))
res1 = torch.nn.functional.one_hot(data[0], 88)
res2 = torch.nn.functional.one_hot(data[1], 88)
print(type(res1))
#res = t.Tuple[res1, res2]
res=tuple([res1, res2])
#res = torch.Tensor([torch.nn.functional.one_hot(data[0], 88), torch.nn.functional.one_hot(data[1], 88)])
print(res)
print(type(res))
print(res1.shape)


<class 'tuple'>
<class 'torch.Tensor'>
(tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]))
<class 'tuple'>
torch.Size([246, 88])


In [55]:
data = dataset[8]
print(data[0])
res1 = torch.nn.functional.one_hot(data[0], 88)
res = torch.argmax(res1, dim=1, keepdim=False)
print(res1)
print(res)

tensor([ 1,  7,  1, 10, 16, 10,  6,  7,  2,  5,  4,  1,  7,  1,  8, 11,  8,  6,
         5,  2,  7,  4,  1,  7, 18,  1,  9,  8,  2,  6,  5,  2,  7,  4,  1, 23,
         1, 16, 17,  6, 28, 16, 17,  4,  1,  7,  1, 10, 16, 10,  6,  7,  2,  5,
         4,  1,  7,  1,  8, 11,  8,  6,  5,  2,  7,  4,  1,  7,  1,  9,  8,  2,
         6, 11,  2,  9,  4,  1, 23,  1, 12, 17,  6, 28, 12,  2, 12,  4,  1,  7,
         1,  9,  8,  2,  6,  5,  2,  7,  4,  1, 23,  1, 11,  2,  9,  6, 12,  9,
        11,  4,  1,  7,  1,  9,  8, 11,  6,  1, 23,  1,  5,  2,  7,  4,  1,  5,
        21,  1, 16, 17,  6,  1, 10, 18,  1,  7,  2, 16,  4,  1,  7,  1, 10, 16,
        10,  6,  7,  2,  5,  4,  1,  7,  1,  8, 11,  9,  6,  1, 23,  1, 12,  9,
        11,  4,  1,  5, 21,  1,  9,  8, 11,  6,  1, 10, 18,  1,  5,  2,  7,  4,
         1,  7,  1,  7, 17,  6, 28,  7,  2,  4])
tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
  